### ISSUE TITLE
【建议】对怪物掉落物的收集

### ISSUE THREAD

**Issue by Noogear** [ranminecraft/ChunkHopper#2]
大佬为什么不加个对怪物掉落物收集的功能？我看了一下代码为啥会做不到呀

**Comment by RanMinecraft** [comment]
是可以做到的，可以监听一下EntityDropItemEvent或者EntityDeathEvent，有空之后我看看

**Comment by Noogear** [comment]
谢谢大佬，还有一件事就是在获取漏斗customname的时候得判断一下是不是null，不然破坏和放置普通漏斗会报错，这是我目前测出来的问题

**Comment by Noogear** [comment]
谢谢大佬，还有一件事就是在获取漏斗customname的时候得判断一下是不是null，不然破坏和放置普通漏斗会报错，这是我目前测出来的问题

**Comment by RanMinecraft** [comment]
> 谢谢大佬，还有一件事就是在获取漏斗customname的时候得判断一下是不是null，不然破坏和放置普通漏斗会报错，这是我目前测出来的问题

修复了 我在1.21.1没遇到你是什么版本的呀

**Comment by Noogear** [comment]
> > 谢谢大佬，还有一件事就是在获取漏斗customname的时候得判断一下是不是null，不然破坏和放置普通漏斗会报错，这是我目前测出来的问题
> 
> 修复了 我在1.21.1没遇到你是什么版本的呀

leaf1.21.1，放置和破坏普通漏斗会报错

**Comment by Noogear** [comment]
> > 谢谢大佬，还有一件事就是在获取漏斗customname的时候得判断一下是不是null，不然破坏和放置普通漏斗会报错，这是我目前测出来的问题
> 
> 修复了 我在1.21.1没遇到你是什么版本的呀

是在BlockBreakEvent和BlockPlaceEvent里的，监听放置和破坏的时候会检测一次漏斗名字就报错了

**Comment by RanMinecraft** [comment]
修复的了

**Comment by Noogear** [comment]
> 修复的了

好像没修，是239和292行chunkYml.contains(hopper.getCustomName())会报null，不过现在的版本我还没测试过

**Comment by Noogear** [comment]
还是有，难道这是leaf的问题？直接在这一行前面加if (hopper.getCustomName()==null) return;就行了，看起来对功能也不会有影响
```java
[23:03:07 ERROR]: Could not pass event BlockPlaceEvent to ChunkHopper vRelease 3.9
java.lang.IllegalArgumentException: Path cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.0-jre.jar:?]
        at org.bukkit.configuration.MemorySection.getDefault(MemorySection.java:859) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.get(MemorySection.java:237) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.contains(MemorySection.java:121) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.contains(MemorySection.java:116) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at ranmc-1.3-shaded.jar/cc.ranmc.hopper.Main.onBlockPlaceEvent(Main.java:239) ~[ranmc-1.3-shaded.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:459) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:487) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:605) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2031) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1555) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1533) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1526) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1484) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1491) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[23:03:09 ERROR]: Could not pass event BlockBreakEvent to ChunkHopper vRelease 3.9
java.lang.IllegalArgumentException: Path cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.0-jre.jar:?]
        at org.bukkit.configuration.MemorySection.getDefault(MemorySection.java:859) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.get(MemorySection.java:237) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.contains(MemorySection.java:121) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.contains(MemorySection.java:116) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at ranmc-1.3-shaded.jar/cc.ranmc.hopper.Main.onBlockBreakEvent(Main.java:292) ~[ranmc-1.3-shaded.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:215) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1941) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1555) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1533) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1526) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1484) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1491) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-143e402]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by Noogear** [comment]
> 修复的了

我测了半天终于发现问题所在了https://github.com/ranminecraft/ChunkHopper/commit/61ba376f58c241e000abdb6fc03bba1043dbc767
你这个修反了，这个判断是漏斗有名字就return了，原来的就好好的不会报错
然后我还看了一下怪物掉落物品事件能不能正常触发，答案是不能，测试代码如下
```java
    @EventHandler
    private void onEntityDropItemEvent(EntityDropItemEvent event) {
        Bukkit.getConsoleSender().sendMessage("A1");
        if (!enable && !getConfig().getBoolean("entity", true)) return;
        Bukkit.getConsoleSender().sendMessage("A2");
        hopper(event.getEntity().getLocation());
    }

    @EventHandler
    private void onEntityDeathEvent(EntityDeathEvent event) {
        Bukkit.getConsoleSender().sendMessage("B1");
        if (!enable && !getConfig().getBoolean("entity", true)) return;
        Bukkit.getConsoleSender().sendMessage("B2");
        hopper(event.getEntity().getLocation());
    }
```
    怪物死亡且掉落物品的时候，控制台只显示了B1 B2，所以用EntityDeathEvent可能更好一点
